baseURL: 'https://blog.ubucon.asia'
languageCode: en
title: 'UbuCon Asia Blog'
theme: "ubuntu-blog-hugo"
buildFuture: true
pagination:
  pagerSize: 5
outputs:
  home:
  - html
  - rss
  - json
  section:
  - html
  - rss
  - json
  taxonomy:
  - html
  - rss
  - json
  term:
  - html
  - rss
  - json
params:
  shortTitle: Blog
  contact: contact@ubucon.asia
  facebook: ubuconasia
  x: UbuConAsia
  github: ubucon-asia
  launchpad: ubucon-asia
  youtube: https://www.youtube.com/@UbuConAsia
  source_repo: https://github.com/ubucon-asia/blog.ubucon.asia
  discourse: https://discourse.ubuntu.org/
defaultContentLanguage: en
languages:
  en:
    languageName: English
    title: UbuCon Asia Blog
    weight: 2
    params:
      shortTitle: Blog
      description: >-
        Latest news from UbuCon Asia Committee
      copyright: >-
        © 2021-Present UbuCon Asia Committee
        Except where otherwise noted, Website source code licensed under MIT, Contents licensed under CC BY-SA 4.0. 
        Ubuntu and Canonical are registered trademarks of Canonical Ltd.
      main_slide:
        label: About the community
        link: about
    menu:
      main:
      - identifier: tags
        name: Tags
        weight: 2
        url: /tags
      - identifier: subscribe
        name: Subscribe(RSS)
        weight: 3
        url: /index.xml
      - identifier: contribute
        name: Contributing to this blog
        weight: 4
        url: /contribute
      link:
      - identifier: home
        name: Homepage
        weight: 1
        url: https://www.ubucon.asia
     
